extractor:
  source:
    datasource:
      url: ...
      username: ...
      password: ...
      driverClassName: ...
  target:
    datasource:
      url: ...
      username: ...
      password: ...
      driverClassName: ...